256 instructions from hell
MMXVII/mmix pull request #15
Opened 2017-01-28 21:03 UTC by KarolinePlum

Concerning Issue #7 

I created all files for the instructions, including the functions which are left unimplemented!(). I also listed them all in the mapping array. However I did not comment the array stating the opcode in hexadecimal and decimal. If someone else feels the need to do that, have fun...

2017-01-28 21:38 UTC, teiesti requested changes
Very good job! You must have had a long day... ;-)

2017-01-28 21:38 UTC, teiesti commented on src/machine/behavior/is/arithmetic/mod.rs
> +mod addi;
It would be nice if we write a macro to reduce this code!

2017-01-28 21:38 UTC, teiesti commented on src/machine/behavior/is/mod.rs
> +    interrupt::trap,
I would like to see a comment like `// PUSHGOI #BF 191` behind every line.

2017-01-28 21:38 UTC, teiesti commented on src/machine/behavior/is/other/mod.rs
> +pub use self::swym::swym;
A newline is missing here!

2017-01-28 21:38 UTC, teiesti commented on src/machine/behavior/is/mod.rs
> +    arithmetic::addu16,
As I see, you really changed the order of addu and 16 to fit into Rust's name scheme. I don't really like that but as long as I have no better option I support to go ahead with that.

Does someone else have an idea?

2017-01-28 21:46 UTC, teiesti commented on src/machine/behavior/is/other/mod.rs
> +pub use self::swym::swym;
Btw: This makes Travis CI fail...

2017-01-29 08:56 UTC, KarolinePlum commented on src/machine/behavior/is/mod.rs
> +    interrupt::trap,
Yes, as written in the pull request's description, if you feel that this is worth two hours of you your time, then you can do that. If you see a ways to do it faster, please tell me ;)

2017-01-29 10:00 UTC, KarolinePlum commented on src/machine/behavior/is/arithmetic/mod.rs
> +mod addi;
Done!

2017-01-29 10:18 UTC, teiesti commented on src/machine/behavior/is/mod.rs
> +    interrupt::trap,
To be honest: I have not seen that you wrote that within the pull request's description.

For the moment: I will approve these changes if we add an issue for that. If I have time in the end, I will write all these comments.

For the one who writes the comments: There is a programming technique called meta-programming. You write a program that writes programs. I use this technique with bash, the pipe (|), sed, egrep, cat, ...

2017-01-29 10:22 UTC, teiesti commented on src/machine/behavior/is/arithmetic/mod.rs
> +mod addi;
Great!

2017-01-29 10:23 UTC, teiesti approved these changes

2017-01-29 11:53 UTC, LukasKalbertodt commented
"269 files changed"... for Rust projects it's rather unusual to have that many small files. As I mentioned in the lecture once, files with 1000 to 2000 lines of code are not too unusual in large projects. I think I would reduce the depth of the module tree by one: defining all arithmetic-instruction functions in `arithmetic.rs` instead of using one file per instruction (the same goes for other branches of the tree).

I wouldn't really mind if you won't change it now, as probably a lot of time was already spent on creating this PR. But I think in this case, fewer bigger files would be more *rusty*. Any opinions on this @jonas-schievink?

2017-01-29 12:07 UTC, jonas-schievink commented
@LukasKalbertodt I usually have few large files instead of ond for each small opcode. On the other hand, I'd imagine this scheme to be easier to navigate (think IDEs without go-to-definition). Personally, I'm fine with either layout.

2017-01-29 12:15 UTC, LukasKalbertodt commented
But I guess all IDEs/editors can search for text... and `[ctrl] + [f] + "fn my_func"` is not too hard? Side note, if you're using Sublime: you can fuzzy search for symbol definitions (structs, functions, ...) with `[ctrl] + [r]`.

And as I said: I don't have a particularly strong opinion on this. The group may decide 😉  I just haven't seen a Rust project with that many files yet (except for maybe the Rust compiler).

2017-01-29 12:35 UTC, BarbaraButz reviewed
So, shall we put all of the instructions in one file?
I would volunteer ~~as a tribute~~ to do that job, but only if we won't change that again. 😅

2017-01-29 13:09 UTC, jonas-schievink commented
@LukasKalbertodt I mean it makes it easier to look at multiple opcode impls at the same time (no need to jump around a single file), but sure, `Ctrl+F` ough to work in most cases.

2017-01-29 13:43 UTC, LukasKalbertodt commented
@jonas-schievink Most editors support multiple *views* into one file... (Sublime, too). On the other hand, I'm often confused by multiple views myself 😁 I don't care how you do it 😉 

But if you change it, I would probably write a script to do most of the dull work.

2017-01-29 17:45 UTC, teiesti commented
I really DO NOT LIKE big files since they always cause trouble:
  - Imagine you want to compare two instruction: If you have two files, you can easily open two windows. If you have a big file, you need to scroll in some editors since they do not allow to open a single file multiple times. (You can also compare two instructions with `diff <fileA> <fileB>`).
  - Sharing work is easier since one file is only edited by one person. This makes merge conflicts appear less often. Also the commit messages tell more since a filename gives detailed information about what was changed.
  - We can write an (inlined) submodule "tests" for each of these files to easily test a single instruction. (Therefore the file will not be that small in the end.)

In my world, a file needs to fit onto a screen no matter what the Rust philosophy says... ;-)

2017-01-29 17:50 UTC, teiesti commented
@LukasKalbertodt: I have overseen that you wrote
> Most editors support multiple views into one file... (Sublime, too).

so I wrote
> If you have a big file, you need to scroll in some editors since they do not allow to open a single file multiple times.

The fact is: There are editors that do not support multiple views. And even if they do, it is confusing... ;-)

2017-01-29 18:45 UTC, jaborn approved these changes

2017-01-30 14:58 UTC, merged