Implemented bitwise-instructions
MMXVII/mmix pull request #24
Opened 2017-02-01 23:14 UTC by BarbaraButz

Please merge #23 first.
Also check the mux[i] and sadd[i] instructions especially careful for mistakes.

2017-02-01 23:35 UTC, BarbaraButz commented
I didn't manage to update the branch without merging/ with only rebasing. Pls help.

2017-02-05 12:19 UTC, teiesti requested changes

2017-02-05 12:19 UTC, teiesti commented on src/machine/behavior/is/bitwise/and.rs
> +/// bitwise and
I think, the doc-comments should be a little bit more detailed. But I suggest to do this in the end, when we have finished the other task.

2017-02-05 12:19 UTC, teiesti commented on src/machine/behavior/is/bitwise/mux.rs
> +    // Execute
There is a newline missing.

2017-02-05 12:19 UTC, teiesti commented on src/machine/behavior/is/bitwise/sadd.rs
> +    super::andn(state, x, y, z);
I am not sure if it is a good idea to call another instruction from here!

2017-02-07 17:20 UTC, KarolinePlum commented on src/machine/behavior/is/bitwise/sadd.rs
> +    super::andn(state, x, y, z);
Why not?

2017-02-08 08:50 UTC, teiesti commented on src/machine/behavior/is/bitwise/sadd.rs
> +    super::andn(state, x, y, z);
What if we want to implement instruction tracing within these functions?

2017-02-08 14:48 UTC, KarolinePlum commented on src/machine/behavior/is/bitwise/sadd.rs
> +    super::andn(state, x, y, z);
Wouldn't that mean lots of redundant code?
Why not simply trace which function is called by the control unit? I'm not sure that I've understood correctly what you mean with "instruction tracing".

2017-02-09 02:03 UTC, BarbaraButz commented
I will implement the requested changes (except for documentation) as soon as the function-call-issue is resolved.

2017-02-09 10:26 UTC, teiesti commented on src/machine/behavior/is/bitwise/sadd.rs
> +    super::andn(state, x, y, z);
@KarolinePlum is right: You can call instructions from other instructions.

2017-02-11 15:33 UTC, teiesti requested changes

2017-02-11 15:33 UTC, teiesti commented on src/machine/behavior/is/bitwise/saddi.rs
> +    // calculate andn and load result
Woud be nice, if this starts with a capital letter.

2017-02-15 15:06 UTC, teiesti requested changes

2017-02-15 15:06 UTC, teiesti commented on src/machine/behavior/is/bitwise/sadd.rs
> +    while bits != 0 {
I am pretty sure this implementation is not right.

2017-02-15 15:06 UTC, teiesti commented on src/machine/behavior/is/bitwise/saddi.rs
> +    while bits != 0 {
Same as SADD.

2017-02-15 15:56 UTC, BarbaraButz commented on src/machine/behavior/is/bitwise/sadd.rs
> +    while bits != 0 {
Not wrong, but unnecessary complicated. Will prettify.

2017-02-15 16:18 UTC, teiesti approved these changes

2017-02-15 16:18 UTC, merged