Implemented arithmetic-instructions
MMXVII/mmix pull request #26
Opened 2017-02-02 21:02 UTC by jaborn

I implemented some of the arithmetic instructions:
- add/ addu/ addu2/ addu4/ addu8/ addu16
- sub/ subu
- cmp/cmpu
- div
- mul/ mulu
-neg/ negu
Implementing for example "mulu" I had some problems because a value need to be stored in a special register. Therefor I want to use "put" but I am not sure of how to commit the value as the value refers to the operand y and z. So please have especially a look at this.

2017-02-02 21:11 UTC, jonas-schievink commented
May I ask how you test the implemented instructions?

2017-02-02 21:34 UTC, jaborn commented
We talked about adding tests on the instructions but we only discussed it once at the beginning. I guess this would be very useful to do it that way so that we know that the functionality is correct.

2017-02-02 22:23 UTC, jonas-schievink commented
When I implement an emulator I always make sure to grab a runnable ROM right at the beginning and try to make it run. That way, I implement the instructions needed by the program (and skip the more obscure ones until later). I highly recommend that (or a similar) approach, since *nothing* is harder to debug than a wrong opcode implementation (this approach doesn't prevent them, but it's much better than doing no testing).

It also feels much more rewarding when some tracing capabilities are built into the interpreter (printing the current opcode or its semi-disassembled form, as well as parts of the current CPU state). You can literally see the program and CPU *do stuff*.

2017-02-02 22:56 UTC, BarbaraButz requested changes
You need to remove some trailing whitespace to content Travis.
`>>> Seaching for lines with trailing whitespaces...	Error.
Found:	./src/machine/behavior/is/arithmetic/cmp.rs
Found:	./src/machine/behavior/is/arithmetic/neg.rs`

2017-02-03 11:16 UTC, teiesti commented
> Implementing for example "mulu" I had some problems because a value need to be stored in a special register. Therefor I want to use "put" but I am not sure of how to commit the value as the value refers to the operand y and z.

If you perform a multiplication, the result can have twice the size of the operands (because 2^64 * 2^64 == 2^(64+64) == 2^(2*64) == 2^128). 128 bit do not fit into a 64 bit-register, therefore MUL throws the upper half away. But MULU stores the upper half in the register rH ("himult").

What you have to do is:

1. Fetch the operands from $Y and $Z, as always.
2. Calculate the lower half.
3. Calculate the upper half. That might be a bit tricky since there is no operation to do that. You have to do some bit shifting.
4. Store the lower half in $X.
5. Store the upper half in rH.

The special register rH can be accessed in the following manner:
```rust
state.sr[R::H] = /*<some rvalue>*/;
```

About using PUT: Please don't do that! PUT needs to check if the special register is accessible. And PUT adds an unnecessary level of indirection.

> We talked about adding tests on the instructions but we only discussed it once at the beginning. I guess this would be very useful to do it that way so that we know that the functionality is correct.

The idea is, that every "instruction file" (like e.g. src/machine/behavior/is/arithmetic/add.rs) includes a test module that looks like this:

```rust
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn some_test() {
        // do some test
    }

    // do more tests

}
```

2017-02-03 11:29 UTC, teiesti commented
FYI: [There are efforts to include a u128 into Rust.][10] That would make our life much easier here. But as long as this feature is not available we have to emulate the behavior...

[10]: https://github.com/rust-lang/rfcs/blob/master/text/1504-int128.md

2017-02-03 12:07 UTC, teiesti requested changes

2017-02-03 12:07 UTC, teiesti commented on src/machine/behavior/is/arithmetic/add.rs
> +    let res = op1 + op2;
What happens to the overflow?

2017-02-03 12:07 UTC, teiesti commented on src/machine/behavior/is/arithmetic/addu.rs
> +    // execute
It would be nice if these comments start with a capital letter (since they are some kind of heading). It would also be nice if the "code blocks" have trailing newlines. This would bring more structure. Example:

```rust
pub fn addu(state: &mut State, x: u8, y: u8, z:u8) {
    // Load operands
    let op1: u64 = state.gpr[y].into();
    let op2: u64 = state.gpr[z].into();

    // Execute
    let res = op1.wrapping_add(op2);

    // Store results
    state.gpr[x] = res.into();
}
```

2017-02-03 12:07 UTC, teiesti commented on src/machine/behavior/is/arithmetic/cmp.rs
> +    if op1 < op2 {
Try this:

```rust
// Load operands
let op1: i64 = state.gpr[y].into();
let op2: i64 = state.gpr[z].into();

// Execute
let res: i64 = op1.cmp(&op2) as i64;

// Store results
state.gpr[x] = res.into();
```

See [here][10] and [here][20] and [here][30] to understand why that works.

[10]: https://doc.rust-lang.org/src/core/cmp.rs.html#200-210
[20]: https://doc.rust-lang.org/book/casting-between-types.html
[30]: http://rustbyexample.com/custom_types/enum/c_like.html

2017-02-03 12:07 UTC, teiesti commented on src/machine/behavior/is/arithmetic/cmpu.rs
> +    if dif > 0 {
--> CMP

2017-02-03 12:07 UTC, teiesti commented on src/machine/behavior/is/arithmetic/div.rs
> +    	put(state, (op1 as u8), 6, 0);
Please do not use PUT here. Details are explained in my long comment.

2017-02-03 12:07 UTC, teiesti commented on src/machine/behavior/is/arithmetic/mul.rs
> +    let res = op1 * op2;
Panics on overflow (in debug mode). Should wrap (if I understand it right).

2017-02-03 12:07 UTC, teiesti commented on src/machine/behavior/is/arithmetic/mulu.rs
> +    	let rh: u8 = (2 as u8).pow(64).wrapping_sub(op1 as u8);
I don't think, this is right!

2017-02-03 12:07 UTC, teiesti commented on src/machine/behavior/is/arithmetic/neg.rs
> +    let res = (y as i64) - op2;
What happens to the overflow?

2017-02-03 12:07 UTC, teiesti commented on src/machine/behavior/is/arithmetic/sub.rs
> +    let res = op1 - op2;
What happens to the overflow?

2017-02-03 12:37 UTC, jonas-schievink commented on src/machine/behavior/is/arithmetic/cmp.rs
> +    if op1 < op2 {
Wow that's neat!

2017-02-03 16:33 UTC, jaborn commented on src/machine/behavior/is/arithmetic/addu.rs
> +    // execute
I will change most of them along with other corrections and I won't make a special commit for it. I hope this is ok.

2017-02-04 10:39 UTC, teiesti requested changes

2017-02-04 10:39 UTC, teiesti commented on src/machine/behavior/is/arithmetic/div.rs
> +        state.gpr[x] = (0 as i64).into();
Try this:

```rust
state.gpr[x] = 0i64.into();
```

2017-02-04 10:39 UTC, teiesti commented on src/machine/behavior/is/arithmetic/mulu.rs
> +    let upp_res = upp_op1.wrapping_mul(upp_op2);
I still don't think that is right. I will do the theory a little later.

2017-02-04 10:48 UTC, jonas-schievink commented on src/machine/behavior/is/arithmetic/mulu.rs
> +    let upp_res = upp_op1.wrapping_mul(upp_op2);
I suggest you just skip MULU for now, it's probably not used widely.

2017-02-04 11:21 UTC, jaborn commented on src/machine/behavior/is/arithmetic/mulu.rs
> +    let upp_res = upp_op1.wrapping_mul(upp_op2);
Ok. I will skip 'divu' as well because it is the same thing and work on it at the end.

2017-02-04 12:35 UTC, teiesti commented
Why so fast with MULU?

2017-02-04 14:25 UTC, BarbaraButz approved these changes

2017-02-04 19:15 UTC, teiesti requested changes

2017-02-04 19:15 UTC, teiesti commented on src/machine/behavior/is/arithmetic/mului.rs
> +
A reference to the theory in the other file would be nice!

2017-02-09 18:22 UTC, teiesti approved these changes

2017-02-09 18:25 UTC, teiesti commented
I have rebased this branch to be able to merge. And I have made some last polishing changes. This is your last chance to review this pull-request: If there is no issue until tomorrow morning, I will merge this branch... ;-)

2017-02-10 11:31 UTC, merged