SRegisters and GPRegisters implemented
MMXVII/mmix pull request #34
Opened 2017-02-10 11:20 UTC by KarolinePlum

2017-02-11 15:49 UTC, teiesti requested changes

2017-02-11 15:49 UTC, teiesti commented on src/machine/state/gpr.rs
> +pub struct GPRegisters(Vec<Octa>);
I was using a struct instead of a tuple struct in the memory implementation. Do we want to have that uniform?

2017-02-11 15:49 UTC, teiesti commented on src/machine/state/sr.rs
> +#[derive(Debug, PartialEq, Copy, Clone)]
Why do we need PartialEq here? Why not Eq or nothing at all?

2017-02-11 15:49 UTC, teiesti commented on src/machine/state/sr.rs
> +        self.0.index(i as usize)
Why do you first cast to u8 and then to usize. What's about

```rust
self.0.index(index as usize);
```

or

```rust
let pos: usize = index.into();
self.0.index(pos)

2017-02-12 20:35 UTC, KarolinePlum commented on src/machine/state/sr.rs
> +#[derive(Debug, PartialEq, Copy, Clone)]
I included `PartialEq` because you need that for `assert_eq!()`

2017-02-12 20:39 UTC, KarolinePlum commented on src/machine/state/gpr.rs
> +pub struct GPRegisters(Vec<Octa>);
I like it more as a tuple struct, but I can change it.

2017-02-12 20:40 UTC, KarolinePlum commented on src/machine/state/sr.rs
> +#[derive(Debug, PartialEq, Copy, Clone)]
For `assert_eq!()`

2017-02-12 20:42 UTC, KarolinePlum commented on src/machine/state/sr.rs
> +        self.0.index(i as usize)
The second proposal does not compile.
I thought that as we implemented .into() for u8 we might as well use it.

2017-02-14 13:56 UTC, KarolinePlum commented on src/machine/state/gpr.rs
> +pub struct GPRegisters(Vec<Octa>);
I find it hard to come up with a name for the field of the struct.

2017-02-14 14:42 UTC, BarbaraButz approved these changes

2017-02-14 16:37 UTC, teiesti approved these changes

2017-02-14 16:37 UTC, teiesti commented on src/machine/state/sr.rs
> +#[derive(Debug, PartialEq, Copy, Clone)]
I think, we should derive `Eq` here, too.

2017-02-14 16:37 UTC, teiesti commented on src/machine/state/gpr.rs
> +            buf: vec![0u64.into(); 256]
There is a comma `,` missing... ;-)

2017-02-14 16:38 UTC, teiesti commented
@KarolinePlum: Please rebase this branch and resolve the outstanding issues before merging it!

2017-02-14 17:01 UTC, merged