Unit tests for memory
MMXVII/mmix pull request #35
Opened 2017-02-10 13:12 UTC by KarolinePlum

2017-02-10 14:27 UTC, LukasKalbertodt commented on src/machine/state/mem.rs
> +    fn it_works() {
Maybe you forgot to change this name to a non dummy one?

2017-02-10 15:47 UTC, teiesti commented
Merges like 1a4efcf should not happen since they make the history very hard to read. A rebase is better. You can correct that with `git reset`, `git cherry-pick` and `git push -f` but be very careful with these commands because they can destroy data.

2017-02-10 15:51 UTC, LukasKalbertodt commented
AFAIK, a rebase will sometimes remove merge commits from the history. So just try to rebase first, before using more dangerous commands ;-)

2017-02-11 17:49 UTC, teiesti requested changes

2017-02-11 17:49 UTC, teiesti commented on src/machine/state/mem.rs
> +#[derive(Copy, Clone, Debug, PartialEq)]
Why do we need Debug?
Why PartialEq? Why not Eq?

2017-02-11 17:49 UTC, teiesti commented on src/machine/state/mem.rs
> +    fn mem_test() {
It think, you combine more than one test within this function! I suggest to split them!

2017-02-11 17:49 UTC, teiesti commented on src/machine/state/mem.rs
> +        for i in 0 .. 16 {
```rust
for i in 0..16
```

2017-02-11 18:05 UTC, teiesti commented
I think we need tests that check if 

1. the memory is initialized with the right capacity:
   - oversized (too large)
   - undersized (too small)
   - allocated in chunks of 64 bits
   - initialized with zeros
2. the index operators work correct
   - no "out of octa" read or write
   - byte order (endianess)
   - esp.: What happens if s.o. write e.g. a Octa first and then reads the Byte, Wyde, Tetra?
3. corner cases are implemented properly
   - "out of bounds" read/write should panic
   - reading or writing the first/last byte should work
4. lifetimes work correctly
   - one mutable reference XOR multiple immutable references

I think we cannot write unit tests, that check number 4. Can we?

Does anybody have more ideas what to test?

2017-02-11 19:33 UTC, jonas-schievink commented
4 can only really be checked via a compile-fail test (a test that makes sure a piece of code is rejected by the compiler), so I suggest to skip it (I've eyeballed the implementation and it should be correct in this regard, you can also easily test manually). If you really want to write such a test then you can use https://github.com/laumann/compiletest-rs

2017-02-15 14:05 UTC, teiesti commented
There is a new pull-request replacing this one. Therefore: Closed.

2017-02-15 14:05 UTC, closed without merging