Implemented other instructions
MMXVII/mmix pull request #38
Opened 2017-02-14 16:33 UTC by jaborn

2017-02-14 16:36 UTC, jonas-schievink commented on src/machine/behavior/is/other/get.rs
> +    	panic!("no register");
What's the real behaviour here? Trap or wrap? (Just curious, I'm not expecting a complete implementation of traps and interrupts)

2017-02-14 16:58 UTC, teiesti commented on src/machine/behavior/is/other/get.rs
> +    	panic!("no register");
The book that we have doesn't say anything about that. It just says z (which must be used here instead of r) is between 0 and 32.

2017-02-14 17:10 UTC, teiesti requested changes

2017-02-14 17:10 UTC, teiesti commented on src/machine/behavior/is/other/get.rs
> +    let r = y.wrapping_add(z);
Don't compute r here. Simply use z as the book says!

2017-02-14 17:10 UTC, teiesti commented on src/machine/behavior/is/other/get.rs
> +    let sr: R = (z as u8).into();
You don't have to panic here. `(z as u8).into()` will panic if the register does not exist.

2017-02-14 17:10 UTC, teiesti commented on src/machine/behavior/is/other/getab.rs
> +    let res: u64 = at + 4 * (ra - 2u64.pow(16u32));
Do not use `pow()` here. Bitshifting is better... ;-)

2017-02-14 17:10 UTC, teiesti commented on src/machine/behavior/is/other/put.rs
> +    let op2: u64 = state.gpr[z].into();
PUT does not use y and z.

2017-02-14 17:10 UTC, teiesti commented on src/machine/behavior/is/other/put.rs
> +    }
Putting is not allowed for any special register. See the table on page 21 for details.

2017-02-14 17:25 UTC, KarolinePlum commented on src/machine/behavior/is/other/getab.rs
> +    let res: u64 = at + 4 * (ra - 2u64.pow(16u32));
I think the compiler will translate this to bitshifting anyway.

2017-02-14 17:48 UTC, jonas-schievink commented on src/machine/behavior/is/other/getab.rs
> +    let res: u64 = at + 4 * (ra - 2u64.pow(16u32));
It will even evaluate the `pow()`-call at compile time so there's just a constant left. Use what you think is more readable.

2017-02-15 14:36 UTC, teiesti commented on src/machine/behavior/is/other/getab.rs
> +    let res: u64 = at + 4 * (ra - 2u64.pow(16u32));
Seems that your right. I verified it in the compiler explorer.

2017-02-15 14:38 UTC, teiesti approved these changes

2017-02-15 14:51 UTC, merged